<a href="https://colab.research.google.com/github/YunChenLi/Tensorflow-Notebook/blob/main/00_tensorflow_fundamentals_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this norebook, we're going to cover some of the most fundamental concepts using Tensorflow.

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @
* Using GPUs with TF


## Introduction to tensors




In [ ]:
# Import Tensorflow

import tensorflow as tf
print(tf.__version__)

2.5.0


In [ ]:
#Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimensions of a tensor (ndim stands for number of dimensions)

scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Create the dimension of our vector

vector.ndim

1

In [ ]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7], [7, 10]])
matrix
 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix 
another_matrix = tf.constant([[10., 7.], [3., 2.],[8., 9.]], dtype = tf.float16) # specify the data type with dtype parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]],
                       [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vecotr: a number with direction ( e.g. wind speed and direction)
* Matrix: a 2-dimentional array of numbers
* Tensor: a n-dimentional array of numbers (when n can be any number, a 0-dimentional tensor is a scalar, a 1-dimentional tensor is a vector)

### Creating tensors with `tf.Variable`


In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
# Create the same tensor with tf.Variable() as above

import tensorflow as tf
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[1].assign(8)
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  8], dtype=int32)>

In [ ]:
# Let's try unchangeable tensor

unchangeable_tensor[0].assign(8)
unchangeable_tensor

AttributeError: ignored

### Create random tensor

Random tensors are tensors of some abitrary size which contain random numbers.

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(5)  # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))#
random_2 = tf.random.Generator.from_seed(5) # random.normal = random w/ normal distribution
random_2 = random_2.normal(shape = (3, 2))

random_1, random_2

# are they equal

random_1, random_2, random_1 == random_2

### Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 7]])
# Shuffle our non-shuffled tensors
tf.random.shuffle(not_shuffled)

In [ ]:
# Shuffle our non-shuffled tensors
tf.random.set_seed(42) # global level seed
tf.random.shuffle(not_shuffled, seed = 42) # operation level seed

# if both global and operation seed are set: Both seeds are used in conjunction to determine the random sequence

**Exercise:** Read through Tensorflow doc on random seed generation:
https://www.tensorflow.org/api_docs/python/tf/random/set_seed 

In [ ]:
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed = 42))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

In [ ]:
tf.random.set_seed(1234)

@tf.function
def f():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

@tf.function
def g():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

print(f())  # prints '(A1, A2)'
print(g())  # prints '(A1, A2)'

In [ ]:
import tensorflow as tf

not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 7]])
tf.random.set_seed(42) # if we set global random seed, we cam the same order at every time 
tf.random.shuffle(not_shuffled, seed = 42) # if we set operation-level random seed, we get different order every time.



### Other ways to get tensors
tf.ones

In [ ]:
tf.ones([10, 7])

# Create a tensor w/ all zeros

tf.zeros([10, 7])

# You can also turn numPy arrays into tensors


### Turn NumPy arrays into tensors

the main difference between Numpy and tensorflow tensors is that tensors can be run on a GPU computing.

In [ ]:
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32) # Create a NumPy array between 1 and 25
numpy_A
# X = tf.constant(some_matrix) # capital for matrix
# Y = tf.constant(vector) # non-capital for vector

In [ ]:
A = tf.constant(numpy_A, shape=(2 ,3, 4))
B = tf.constant(numpy_A)
C = tf.constant(numpy_A, shape=(3, 8))
D = tf.constant(numpy_A, shape=(2,12))
A, B, C
A.ndim, B.ndim, C.ndim, D.ndim
tf.size(A)

### Getting information from tensors


* Shape: tensor.shape
* Rank: tensor.ndim
* Axis or dimenson: tensor[0], tensor[:, 1]
* Size: tf.size(tensor)




In [ ]:
# Create a rank 4 tensor
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor[0]

In [ ]:

rank_4_tensor.ndim, tf.size(rank_4_tensor), rank_4_tensor.shape # numpy = 2*3*4*5=120

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1]) #last axis
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).dtype)

### Indexing tensors

tensors can be indexed just like python lists.

In [ ]:
# Get the first two elements of each dimensions
rank_4_tensor[:2, :2, :2, :2]


In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]
rank_4_tensor[:, :1, :1, :1]

In [ ]:
# Create a rank 2 tensors

rank_2_tensor = tf.constant([[10, 7],
                            [2, 3]])
rank_2_tensor, rank_2_tensor.shape, rank_2_tensor[:,-1]

In [ ]:
# Add dimensions (tf.newaxis, tf.expand_dims)
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor, tf.expand_dims(rank_2_tensor, axis = -1) # "-1" means expand the final axis


### Manipulagting tensors(tensor operations)

** Basic operations **

`+`, `-`, `*`, `/`

In [ ]:
tensor = tf.constant([[10, 7],[3, 4]])
tensor + 10, tensor * 2 # tf.multiply(tensor, 2)

### Matrix multiplication

In ML, matriox multiplication is one of the most common tensor operations.

** Resource: matrix multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

* There are two rules our tensors (or matrices) need to fulfil if we're going to matrix multiply them:

1. the inner dimensions must match
2. the resulting matrix has the shape of the outer dimensions

In [ ]:
tensor, tensor @ tensor, tensor * tensor

In [ ]:
# Try to matrix multiply tensors of same shape
import tensorflow as tf
X = tf.constant([[10, 7],     
                [3, 4]])
Y = tf.constant([[10, 7],     
                [3, 4]])

tf.matmul(X, Y), X @ Y

In [ ]:
# Let's change shapoe (tf.reshape), can do the same with transpose (tf.transpose)

import tensorflow as tf
Z = tf.constant([[10,7,4],[2,3,10],[1, 2, 3]])


X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
X_reshaped = tf.reshape(X, shape=(2, 3)) # witih same amount of values
X_transposed = tf.transpose(X)

X_reshaped @ Z, tf.transpose(X)


** The dot product**

Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`


### Changing a new tensor with default datatype (float32)


In [ ]:
B = tf.constant([1.7, 7.4, 8.6])
C = tf.constant([1.7])
D = tf.constant([1, 7])
E = tf.constant([1., 2.])
B, C, D, E

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.7, 7.4, 8.6], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.7], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>)

In [ ]:
# Change from float32 to float16 (tf.cast)
B = tf.cast(B, dtype=tf.float16)
B


<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1.7, 7.4, 8.6], dtype=float16)>

In [ ]:
B.dtype

tf.float16

### Aggregating tensors

Aggregating tensors = condensing then from multiple values down to a smaller amount of values

In [ ]:
# get an absolute values (tf.abs)
F = tf.constant([-3, -5])
tf.abs(F)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5], dtype=int32)>

In [ ]:
# Create a random tensors with values between 0 and 100 of size 50
import numpy as np
G = tf.constant(np.random.randint(0, 100, size=50))
G


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([97, 74,  8, 17, 31, 29, 92, 67, 71, 84, 77, 54, 33, 98, 10,  9, 94,
        6, 35, 81, 81, 59, 89, 46, 98, 37, 40, 42, 33, 98, 72, 28, 35, 88,
        6, 36, 99, 78, 92, 98, 77, 59, 43, 33, 44,  8, 61, 22, 12, 19])>

In [ ]:
tf.size(G), G.shape, G.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# Find min, max, mean, sum
tf.reduce_min(G), tf.reduce_max(G), tf.reduce_mean(G), tf.reduce_sum(G)

(<tf.Tensor: shape=(), dtype=int64, numpy=6>,
 <tf.Tensor: shape=(), dtype=int64, numpy=99>,
 <tf.Tensor: shape=(), dtype=int64, numpy=54>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2700>)

In [ ]:
# Find  (tfp.stats.variance, tf.math.reduce_std) - To define variance of our tensor, we need access to tensorflow_probability
import tensorflow_probability as tfp
tfp.stats.variance(G), tf.math.reduce_std(tf.cast(G, dtype = tf.float32)) # define standard deviation

(<tf.Tensor: shape=(), dtype=int64, numpy=941>,
 <tf.Tensor: shape=(), dtype=float32, numpy=30.67768>)

### Find the position maximum and minimum


In [ ]:
# Create a new tensor for finding positional min and max
import tensorflow as tf
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F, tf.argmax(F)

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, <tf.Tensor: shape=(), dtype=int64, numpy=42>)

In [ ]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Find the max value 
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Find the positional min, min value
tf.argmin(F), F[tf.argmin(F)]

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

### Sequencing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor 
G = tf.constant(tf.random.uniform(shape=[50]), shape = (1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [ ]:
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       dtype=float32)>, TensorShape([50]))

### One-hot encoding tensors



In [ ]:
# Create a list of indices 👏🏻
some_list = [0, 1, 2, 3] # could be red, blue, yellow, purple

# One hot encoding our list of indices
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding 
tf.one_hot(some_list, depth=4, on_value="yo I love DL", off_value="I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love DL', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo I love DL',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo I love DL', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo I love DL']], dtype=object)>

In [ ]:
# Test 💕
Jack_list = [0, 1]
tf.one_hot(Jack_list, depth=2), tf.one_hot(Jack_list, depth=2, on_value= "I love Jack", off_value="I like him")

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 0.],
        [0., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=string, numpy=
 array([[b'I love Jack', b'I like him'],
        [b'I like him', b'I love Jack']], dtype=object)>)

### Squaring, log, square root

In [ ]:
# Create a new tensor (tf.math.sqrt, tf.math.log)
H = tf.range(1, 10)
H, tf.math.sqrt(tf.cast(H, dtype=tf.float32)), tf.math.log(tf.cast(H, dtype=tf.float32))

(<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
        2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
        1.9459102, 2.0794415, 2.1972246], dtype=float32)>)

### Tensor and NumPy

Tensorflow beautifullt interats with NumPy array

In [ ]:
# Create a tensor directly from a NumPy array
import numpy as np

J = tf.constant(np.array([3., 7., 10.]))
J

# Convert tensor J to a Numpy array
np.array(J), type(np.array(J))

# Convert tensor J to a Numpy array
J.numpy(), type(J.numpy()), np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray, array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# The default type of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
# Check the datatype of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

tf.config.list_physicl_device()

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices()

# nvidia smi to check GPU

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]